### ISSUE TITLE
Compile for windows

### ISSUE THREAD

**Issue by wadixx** [xixogo5105/uiptv#3]
I'm not familiar with java. Took my chance but couldn't figure it out. Can you compile it for windows please?

**Comment by xixogo5105** [comment]
you need to have JDK installed as well JDK path configured (under Environment Variables)
then download the binary (x86_64) from https://github.com/xixogo5105/uiptv/releases/download/uiptv-logo/windows-uiptv.zip
extract the binary files into a folder and then go to that folder/directory in the terminal and run the below command.

call java --module-path .\lib --add-modules=javafx.controls -jar .\UIPTV.jar

**Comment by xixogo5105** [comment]
compilation should also be very simple 
just download maven and configure it

to verify if it installed properly type:
mvn --version
you should a message like this:
Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)
Maven home: X:\Programs\apache-maven-3.8.8
Java version: 17.0.9, vendor: Oracle Corporation, runtime: X:\Programs\jdk-17.0.9
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

then go to source code folder and type "mvn clean install" that all. additional details regarding the files to copy are present on the home page

**Comment by xixogo5105** [comment]
a windows executable is available for release 5 & 6. hence closing this defect
