### ISSUE TITLE
ENTER hotkey on channel list does not play the channel

### ISSUE THREAD

**Issue by gamicoulas** [xixogo5105/uiptv#4]
Pressing Enter on a selected channel on the list does not play the channel as the mouse double click action.
I see that there is an event handler for the Enter key in the addChannelClickHandler(), but I wonder if the use of an operator == instead of an equals() method is to blame.

Would there be any chance of adding the Enter key handler on the Account and Categories lists also?

Thanx for your efforts. Lovely app BTW. Greatly appreciated...

**Comment by xixogo5105** [comment]
Yes. this is a bug. it seems like row level event is not working.

**Comment by xixogo5105** [comment]
fixed/added Enter key functionality for bookmark list, account list, category list, channel list and episode list. Fix will be applied to next release

**Comment by xixogo5105** [comment]
Dear OP,

can you please try release 6 and let me know if the reported issue is resolved or not?

**Comment by gamicoulas** [comment]
I'm pleased to inform that the ENTER key is working as expected on all lists on release 6. Many thanks again...
